trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      pip install awscli
      aws configure set aws_access_key_id $(AWS_ACCESS_KEY)
      aws configure set aws_secret_access_key $(AWS_SECRET_KEY)
    displayName: 'Install AWS CLI and configure credentials'

  - script: |
      aws s3 cp index.html s3://<your-bucket-name>/index.html
      aws s3 cp index2.html s3://<your-bucket-name>/index2.html
      aws s3 cp index3.html s3://<your-bucket-name>/index3.html
    displayName: 'Push index.html files to S3'
